# Generated by Django 4.1.3 on 2022-12-30 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_entries', to='store.store')),
            ],
            options={
                'db_table': 'product',
                'unique_together': {('name', 'store')},
            },
        ),
    ]
