# Generated by Django 4.1.3 on 2022-12-30 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('max_capacity', models.PositiveSmallIntegerField(default=0)),
                ('current_capacity', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'material',
            },
        ),
        migrations.CreateModel(
            name='MaterialQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_material_quantity', to='material.material')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_material_quantity', to='product.product')),
            ],
            options={
                'db_table': 'material_quantity',
                'unique_together': {('product', 'material')},
            },
        ),
        migrations.AddField(
            model_name='material',
            name='product',
            field=models.ManyToManyField(related_name='material_entries', through='material.MaterialQuantity', to='product.product'),
        ),
        migrations.AddField(
            model_name='material',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_entries', to='store.store'),
        ),
        migrations.AlterUniqueTogether(
            name='material',
            unique_together={('name', 'store')},
        ),
    ]
