# Generated by Django 4.1.3 on 2022-12-30 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialquantity',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_material_quantity', to='product.product'),
        ),
        migrations.AddField(
            model_name='material',
            name='product',
            field=models.ManyToManyField(related_name='material_entries', through='material.MaterialQuantity', to='product.product'),
        ),
    ]
